version: '3'

services:
    jvb:
        image: jitsi/jvb:stable-6173
        container_name: chama-jvb
        restart: always
        ports:
            - '10000:10000/udp'
            - '4443:4443'
            - '8081:8080'
            - '9090:9090'
            - '4096:4096/udp'
        volumes:
            - /opt/jitsi/jvb/config:/config:Z
        environment:
            - ENABLE_COLIBRI_WEBSOCKET=1
            - ENABLE_OCTO=1              
            - DOCKER_HOST_ADDRESS=161.148.200.169
            - XMPP_AUTH_DOMAIN=auth.chama-homologacao.serpro.gov.br
            - XMPP_INTERNAL_MUC_DOMAIN=internal-muc.chama-homologacao.serpro.gov.br
            - XMPP_SERVER=xmpp.chama-homologacao.serpro.gov.br
            - JVB_AUTH_USER=jvb
            - JVB_AUTH_PASSWORD=3f0e227622f0d5bc42f61f364080a768
            - JVB_BREWERY_MUC=jvbbrewery
            - JVB_PORT=10000
            - JVB_TCP_HARVESTER_DISABLED=false
            - JVB_TCP_PORT=4443
            - JVB_TCP_MAPPED_PORT=4443
            - JVB_STUN_SERVERS=
            - JVB_ENABLE_APIS=rest,xmpp
            - JVB_WS_DOMAIN=chama-homologacao.serpro.gov.br:443
            - JVB_WS_SERVER_ID=jvb1
            - PUBLIC_URL=https://chama-homologacao.serpro.gov.br
            - JVB_OCTO_BIND_ADDRESS=0.0.0.0
            - JVB_OCTO_PUBLIC_ADDRESS=161.148.200.169
            - JVB_OCTO_BIND_PORT=4096
            - JVB_OCTO_REGION=Brasilia      
            - TZ=America/Fortaleza
            - JVB_OPTS=--apis:rest,xmpp
        logging:
          options:
            max-size: "35m"
            max-file: "3"
